/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.glb
Author: Juangamer (https://sketchfab.com/Juangamer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/y-bot-gangnam-e5b94f9df5b347b28bbe560ca8f74764
Title: Y Bot Gangnam
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import pathY from './assets/y_bot/scene.glb'

export default function ModelYBot(props) {
	const group = useRef()
	const { nodes, scene, materials, animations } = useGLTF(pathY)
	const { actions } = useAnimations(animations, group)

	const animation = () => {
		const { mixer } = useAnimations(animations, lisaRef)
	}

	return (
		<>
			<group ref={group} {...props} dispose={null}>
				<group name="Sketchfab_Scene">
					<group
						name="Sketchfab_model"
						rotation={[-Math.PI / 2, 0, -0.2]}
						position={[190, -100, -500]}
					>
						<group
							name="c2635f975bb246ac8bad0887bd9202f3fbx"
							rotation={[Math.PI / 2, 0, 0]}
						>
							<group name="Object_2">
								<group name="RootNode">
									<group name="Object_4">
										<primitive object={nodes._rootJoint} />
										<group name="Alpha_Surface" />
										<group name="Alpha_Joints" />
										<skinnedMesh
											onClick={() => actions['mixamo.com'].reset().play()}
											name="Object_6"
											geometry={nodes.Object_6.geometry}
											material={materials.Alpha_Body_MAT}
											skeleton={nodes.Object_6.skeleton}
										/>
										<skinnedMesh
											name="Object_7"
											geometry={nodes.Object_7.geometry}
											material={materials.Alpha_Joints_MAT}
											skeleton={nodes.Object_7.skeleton}
										/>
									</group>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
			{/* <AnimationController
				scene={scene}
				modelRef={group}
				animations={animations}
			/> */}
		</>
	)
}
